@startuml Use case
left to right direction
actor User as U #yellow
actor Admin as A #lightblue
actor "Super Admin" as SA #pink
rectangle "Reservation Management System" {
    U --> (Login)
    U --> (Signup)
    U --> (View Availability of venues according to the location)
    U --> (View Availability of venues according to the venue type)
    U --> (Reserve a venue)
    U --> (View Summary and State of Reservation)
    U --> (Remove draft venues)
    U --> (Add feedback)
    U --> (Cancel reservation)
    A --> (Login)
    A --> (Update Venue Details)
    A --> (Add new venue details)
    A --> (View the user reservations)
    A --> (Accept/Reject user reservation)
    A --> (Delete the venue)
    A --> (Make availability reservation)  
    A --> (aske question)
    A --> (Generate Reports)
    SA --> (Assign Admin)
}
@enduml